import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  timestamp,
  boolean,
  primaryKey,
  pgEnum,
  jsonb,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// ---------- Enums ----------

export const matchStatus = pgEnum('match_status', ['upcoming', 'in_progress', 'completed']);
export const teamRole = pgEnum('team_role', ['owner', 'coach']);

// ---------- Users & teams ----------

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  name: varchar('name', { length: 120 }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const teams = pgTable('teams', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 120 }).notNull(),
  // Short code used to invite other coaches. Generated by the server.
  inviteCode: varchar('invite_code', { length: 16 }).notNull().unique(),
  createdBy: uuid('created_by').notNull().references(() => users.id, { onDelete: 'restrict' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const teamMembers = pgTable(
  'team_members',
  {
    teamId: uuid('team_id').notNull().references(() => teams.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    role: teamRole('role').notNull().default('coach'),
    joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.teamId, t.userId] }),
  }),
);

// ---------- Players ----------

export const players = pgTable(
  'players',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    teamId: uuid('team_id').notNull().references(() => teams.id, { onDelete: 'cascade' }),
    name: varchar('name', { length: 120 }).notNull(),
    jerseyNumber: integer('jersey_number'),
    photoUrl: text('photo_url'),
    // Accumulated season play time. Coach-editable from the player profile.
    playTimeSeconds: integer('play_time_seconds').notNull().default(0),
    active: boolean('active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    teamJerseyUnique: uniqueIndex('players_team_jersey_unique')
      .on(t.teamId, t.jerseyNumber)
      .where(sql`${t.jerseyNumber} is not null`),
  }),
);

// ---------- Matches ----------

export const matches = pgTable('matches', {
  id: uuid('id').primaryKey().defaultRandom(),
  teamId: uuid('team_id').notNull().references(() => teams.id, { onDelete: 'cascade' }),
  opponent: varchar('opponent', { length: 120 }).notNull(),
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull(),
  halfLengthMinutes: integer('half_length_minutes').notNull(),
  substitutionWindows: integer('substitution_windows').notNull(),
  playerCount: integer('player_count').notNull().default(9),
  goaliePlayerId: uuid('goalie_player_id').references(() => players.id, { onDelete: 'set null' }),
  status: matchStatus('status').notNull().default('upcoming'),
  myScore: integer('my_score'),
  opponentScore: integer('opponent_score'),
  // Timer/state machine for the live runner. Null while the match is upcoming.
  liveState: jsonb('live_state'),
  // Runtime snapshot of who is on the field / bench / sick bay right now.
  // Shape: { currentSegmentIdx, field: [{playerId, slot, isGoalie}], reserves: string[], sickBay: string[] }
  // Null when the match hasn't been begun yet.
  fieldState: jsonb('field_state'),
  createdBy: uuid('created_by').notNull().references(() => users.id, { onDelete: 'restrict' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

// Which players are available for a given match (subset of the roster).
export const matchPlayers = pgTable(
  'match_players',
  {
    matchId: uuid('match_id').notNull().references(() => matches.id, { onDelete: 'cascade' }),
    playerId: uuid('player_id').notNull().references(() => players.id, { onDelete: 'cascade' }),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.matchId, t.playerId] }),
  }),
);

// One segment per game slice. For 3 sub windows → 4 segments. Index is 0-based.
export const matchSegments = pgTable(
  'match_segments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    matchId: uuid('match_id').notNull().references(() => matches.id, { onDelete: 'cascade' }),
    segmentIndex: integer('segment_index').notNull(),
    formation: varchar('formation', { length: 32 }).notNull(),
    playerCount: integer('player_count').notNull().default(9),
  },
  (t) => ({
    uniq: uniqueIndex('match_segments_match_idx_unique').on(t.matchId, t.segmentIndex),
  }),
);

// Player placement inside one segment. Either on the field at a specific slot
// (positionSlot 0..N-1) or in reserve (positionSlot = null, isField = false).
//
// For tabs 2..N we also store which previous-segment position this player is
// taking over from (substitutingForPositionSlot). The UI uses that to colour
// the swap pairs.
export const segmentPositions = pgTable(
  'segment_positions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    segmentId: uuid('segment_id').notNull().references(() => matchSegments.id, { onDelete: 'cascade' }),
    playerId: uuid('player_id').notNull().references(() => players.id, { onDelete: 'cascade' }),
    isField: boolean('is_field').notNull(),
    positionSlot: integer('position_slot'), // null for reserves
    isGoalie: boolean('is_goalie').notNull().default(false),
  },
  (t) => ({
    uniqPlayerPerSegment: uniqueIndex('segment_positions_player_unique').on(t.segmentId, t.playerId),
  }),
);

// ---------- Phase 2 placeholder (created now so future migrations don't need to backfill) ----------
//
// match_events captures everything that happens during the live runner: goals,
// substitutions, notes, half-start/end markers. Stored as jsonb for forward
// compatibility while the event shape is still evolving.
export const matchEvents = pgTable('match_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  matchId: uuid('match_id').notNull().references(() => matches.id, { onDelete: 'cascade' }),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).defaultNow().notNull(),
  matchClockSeconds: integer('match_clock_seconds').notNull(),
  half: integer('half').notNull(),
  eventType: varchar('event_type', { length: 32 }).notNull(),
  payload: jsonb('payload').notNull().default(sql`'{}'::jsonb`),
});
